### ISSUE TITLE
Prompt for tests to run

### ISSUE THREAD

**Issue by ianoc** [bazeltools/bazelfe#106]
Discussed offline, but a possible feature:

Problem:
User runs:
```
bazel test
```

Exit code is zero, don't realize unlike say maven test, this does nothing.

Possible actions/modes:

1) `bazel test` enters an interactive prompt to offer most recent test ran to be ran again, or alternatively look at the most recent edited files in the tree and use bazel query to work out the downstream test/tests and offer those? 

2) `bazel test` errors with no args and offers some of the examples above as possible commands the user could try invoking instead

**Comment by alexeagle** [comment]
Thinking about it a bit more, coming from typical makefiles and package.json, I think `bazel test ${package_name()}/...` is the least surprising thing for this to do if non-interactive (or offer as the first suggestion if interactive)

**Comment by ianoc** [comment]
Doing that in any larger repo would be an anti-pattern I guess. Configuration option to set it seems fine though?

**Comment by ianoc** [comment]
There is a configuration option now for the simple cases of error ++ change to `//...` the `//...` can be overridden in the config to issue something else too.

**Comment by ianoc** [comment]
Closed since use case from original post is being handled by https://github.com/aspect-build/aspect-cli
