### ISSUE TITLE
support for arbitrary regexp -> command-line executions

### ISSUE THREAD

**Issue by siddarth-stripe** [bazeltools/bazelfe#97]
It'd be super helpful to have support for generic error-extraction and out-of-band handling. The specific use-case I'm looking at is around unused imports in protoc. The error is of the form:

```
foo/bar/baz/definition.proto:6:1: warning: Import qux/baz.proto is unused.
```

If we could add support for configuring generic regular expressions (in this case, something like `^(.*):(\d+):(\d+): warning: Import (.*) is unused.$`) along with support for a command (a custom equivalent of `buildifier` in our typical use-case) that'll get dispatched to, that'd be super useful.

Fairly agnostic on how we configure this (be it a `.bazelfe` config file, or command-line args or such), but the hope is to leverage all the great BEP handling bazelfe already does, while allowing for custom plugins. I imagine multi-line support is tricky, but right now, for this use-case, single-line string matches is plenty!

**Comment by ianoc** [comment]
Something is about ~70-80% done in the linked PR. Gives behavior like:
```
 [[error_processors]]
 name = "Identifying unused proto imports"
 active_action_type = "proto_library"
 regex_match =  '^(.*):(\d+):(\d+): warning: Import (.*) but not used.$'
 target_command_line = '''
    "/bin/foo" '{1}' "{2}"
 '''
```

Making the regex match against multiple lines on the impl side isn't really too hard, though harder to write a decent one i guess. At that point might want to send the data to the users executable if we need those cases for it to just parse/extract from stdout/stderr logs themselves. But ... probably won't need it?
